### ISSUE TITLE
read httpresponse body -> attempted read closed stream

### ISSUE THREAD

**Issue by sim1st** [esigate/esigate#131] opened 2015-09-08 08:05 UTC
I modified some code, like FragmentLoggin.java or FecthLogging.java.

Because I want to LOG httpresponse body part, so I used EntityUtils.toString() method to get body as a String type.

I success to LOG body part in "catalina.out" file, but in browser, I got error with "Error retrieving URL" message.
##########################################
Here is my modified code:

 HttpEntity entity = e.getHttpResponse().getEntity();
 InputStream is = null;
 String respBodies = null;
 try {
       respBodies = EntityUtils.toString(entity);
       EntityUtils.consume(entity);
 } catch (IOException ex) {
       ex.printStackTrace();
   }
##############################

And I attached java error log screenshot file
![error](https://cloud.githubusercontent.com/assets/12407436/9729623/9d1d53dc-564b-11e5-8844-cc00a34a613a.PNG)

Any idea to solve this problem?

**Comment by nricheton** [comment] 2015-09-08 09:10
Hi, 

When you read the entity, the stream is consumed. 
Thus, there is no longer data to be read by esigate. 

The workaround is to inject a new response containing the entity you just read. 
You can take a look to other extensions doing something similar, such as HtmlCharsetProcessor

Consider creating a pull request with you changes, it would be nice to have a debug extension showing the whole body of requests & responses.

**Comment by nricheton** [comment] 2015-09-08 09:11
Closing since this is the expected behavior of response & entity.

**Closed by nricheton** 2015-09-08 09:11 UTC

**Comment by sim1st** [comment] 2015-09-10 08:09
Thanks for quick answering.

I made a custom event and Logging extension, and wanted to get Body/header part at one java file(class).

But I can't integrate two part(body and header).

For Body part, I used ReadEntityEvent, For Header part, I used FragmentLogging

How can I integrate to get body value and header value in one java class?

**Comment by fxbonnet** [comment] 2015-09-11 14:01
I think you should bind your extension to FragmentEvent or FetchEvent (if you want to see only the responses from the server and not from the cache). ReadEntityEvent does not give you access to the response with all the headers, only the body.

If your extension consumes the entity, it has to replace it with a new one for the rest of the process. You can do something like that:
```java
HttpEntity entity = httpResponse.getEntity();
// read the body of the response
String body = EntityUtils.toString(entity);
LOG.debug("body=" + body);
// now replace it
HttpEntity newEntity = new StringEntity(body,ContentType.get(entity));
httpResponse.setEntity(newEntity);
```
