### ISSUE TITLE
Redirects return wrong scheme in Location header when esigate is used to terminate https

### ISSUE THREAD

**Issue by annahosanna** [esigate/esigate#132] opened 2015-10-07 02:42 UTC
It seems that when esigate is acting as a reverse proxy and terminating SSL/TLS sessions and forwarding those internally as http - when the internal server sends a redirect (such as a 302) esigate correctly rewrites everything in the Location header except the scheme.  

If the host and port from the original request uri are equal to the host and port from the Location header uri in the Http Response, then the scheme should be the same as the original request.

Thank you

**Comment by fxbonnet** [comment] 2015-10-15 13:16
I just tried to write a new unit tests in class org.esigate.DriverTest and the test passes. Could you attach your esigate.properties file and also set the log to debug and attach the result?
My test looks like this:
```java
    public void testRewriteRedirectResponseHttps() throws Exception {
        Properties properties = new Properties();
        properties.put(Parameters.REMOTE_URL_BASE.getName(), "http://www.foo.com:8080/");
        properties.put(Parameters.PRESERVE_HOST, "false");
        request = TestUtils.createIncomingRequest("https://www.bar.com/foo/");
        HttpResponse response =
                new BasicHttpResponse(new ProtocolVersion("HTTP", 1, 1), HttpStatus.SC_MOVED_TEMPORARILY, "Found");
        response.addHeader("Location", "http://www.foo.com:8080/somewhere/");
        mockConnectionManager.setResponse(response);
        Driver driver = createMockDriver(properties, mockConnectionManager);
        CloseableHttpResponse driverResponse = driver.proxy("/foo/", request.build());
        assertEquals("https://www.bar.com/somewhere/", driverResponse.getFirstHeader("Location").getValue());
    }
```

**Comment by annahosanna** [comment] 2015-11-10 15:33
This is an anonymized version:
# ESIGate is listening on https://testserver.some.domain:8200
# Note the mapping overlap between provider4 and the other providers

extensions=org.esigate.extension.FragmentLogging, org.esigate.extension.FetchLogging, org.esigate.authentication.RemoteUserAuthenticationHandler, org.esigate.extension.Esi, org.esigate.extension.ResourceFixup, org.esigate.extension.XPoweredBy, org.esigate.extension.surrogate.Surrogate, org.esigate.extension.ConfigReloadOnChange

provider1.remoteUrlBase=http://testserver.some.domain:8080/
provider1.mappings=/app1*
provider1.storeCookiesInSession=*
provider1.visibleUrlBase=https://testserver.some.domain:8080/

provider2.remoteUrlBase=http://testserver.some.domain:8090/
provider2.mappings=/app2*
provider2.storeCookiesInSession=*

provider3.remoteUrlBase=http://testserver.some.domain:8100/
provider3.mappings=/app3*
provider3.storeCookiesInSession=*

provider4.remoteUrlBase=http://testserver.some.domain:8120/
provider4.mappings=/*
provider4.stripMappingPath=true
provider4.storeCookiesInSession=*

**Comment by fxbonnet** [comment] 2015-11-10 15:45
Thank you for the configuration file.
Could you also attach a log file with DEBUG level?
On which of the 4 providers does the issue occurs? What is the request URL and the location header content?

**Comment by fxbonnet** [comment] 2016-01-19 13:57
Closing. No information provided in order to reproduce.

**Closed by fxbonnet** 2016-01-19 13:57 UTC
Labels: question
