### ISSUE TITLE
esi:choose executing include in when statement prematurely

### ISSUE THREAD

**Issue by StevenWeathers** [esigate/esigate#116] opened 2015-06-23 04:20 UTC
I'm trying to test an ESI statement that works as far as which ESI it chooses, however its executing calls to the other ESI include as well.

```
<esi:choose>
            <esi:when test="'$(HTTP_COOKIE{username})' != ''">
                <esi:include src="/esi/include/a" />
            </esi:when>
            <esi:otherwise>
                <esi:include src="/esi/include/b" />
            </esi:otherwise>
 </esi:choose>
```

**Comment by fxbonnet** [comment] 2015-06-23 08:40
Hello,
Good catch! I have been able to reproduce this issue. I am working on it.

**Comment by StevenWeathers** [comment] 2015-06-23 19:20
Pulled your changes locally and built, seems to have fixed the issue thanks!

**Comment by StevenWeathers** [comment] 2015-06-23 19:21
Didn't mean to close it, just comment ;)

**Comment by fxbonnet** [comment] 2015-06-24 08:18
Yes, I finished testing on my side, it looks like the issue is solved. I close it.

**Closed by fxbonnet** 2015-06-24 08:18 UTC
Labels: bug
